spring:
  application:
    name: spring-cloud-blog

eureka:
  client:
    healthcheck: true
    fetch-registry: true

    serviceUrl:
      #defaultZone: http://localhost:8761/eureka/
      defaultZone: http://27.96.135.235:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    preferIpAddress: true

server:
  port: 8768